"""SDL_hints.h migration guide - SDL2 to SDL3."""

HEADER = "SDL_hints.h"

MIGRATION_DATA = """
# SDL_hints.h Migration Guide

## Hint Callback Behavior

Calling SDL_GetHint() with the name of the hint being changed from within a hint
callback will now return the new value rather than the old value. The old value
is still passed as a parameter to the hint callback.

## Environment Variable Renames

The environment variables SDL_VIDEODRIVER and SDL_AUDIODRIVER have been renamed
to SDL_VIDEO_DRIVER and SDL_AUDIO_DRIVER, but the old names are still supported
as a fallback.

The environment variables SDL_VIDEO_X11_WMCLASS and SDL_VIDEO_WAYLAND_WMCLASS
have been removed and replaced by either using the appindentifier param to
SDL_SetAppMetadata() or setting SDL_PROP_APP_METADATA_IDENTIFIER_STRING with
SDL_SetAppMetadataProperty()

The environment variable AUDIODEV is used exclusively to specify the audio
device for the OSS and NetBSD audio drivers. Its use in the ALSA driver has been
replaced with the hint SDL_HINT_AUDIO_ALSA_DEFAULT_DEVICE and in the sndio driver
with the environment variable AUDIODEVICE.

## Hint Renames

The following hints have been renamed:

• SDL_HINT_ALLOW_TOPMOST => SDL_HINT_WINDOW_ALLOW_TOPMOST
• SDL_HINT_AUDIODRIVER => SDL_HINT_AUDIO_DRIVER
• SDL_HINT_DIRECTINPUT_ENABLED => SDL_HINT_JOYSTICK_DIRECTINPUT
• SDL_HINT_GDK_TEXTINPUT_DEFAULT => SDL_HINT_GDK_TEXTINPUT_DEFAULT_TEXT
• SDL_HINT_JOYSTICK_GAMECUBE_RUMBLE_BRAKE =>
SDL_HINT_JOYSTICK_HIDAPI_GAMECUBE_RUMBLE_BRAKE
• SDL_HINT_JOYSTICK_HIDAPI_PS4_RUMBLE => SDL_HINT_JOYSTICK_ENHANCED_REPORTS
• SDL_HINT_JOYSTICK_HIDAPI_PS5_RUMBLE => SDL_HINT_JOYSTICK_ENHANCED_REPORTS
• SDL_HINT_LINUX_DIGITAL_HATS => SDL_HINT_JOYSTICK_LINUX_DIGITAL_HATS
• SDL_HINT_LINUX_HAT_DEADZONES => SDL_HINT_JOYSTICK_LINUX_HAT_DEADZONES
• SDL_HINT_LINUX_JOYSTICK_CLASSIC => SDL_HINT_JOYSTICK_LINUX_CLASSIC
• SDL_HINT_LINUX_JOYSTICK_DEADZONES => SDL_HINT_JOYSTICK_LINUX_DEADZONES
• SDL_HINT_VIDEODRIVER => SDL_HINT_VIDEO_DRIVER
• SDL_HINT_VIDEO_WAYLAND_EMULATE_MOUSE_WARP =>
SDL_HINT_MOUSE_EMULATE_WARP_WITH_RELATIVE

## Removed Hints

The following hints have been removed:

• SDL_HINT_ACCELEROMETER_AS_JOYSTICK
• SDL_HINT_ANDROID_BLOCK_ON_PAUSE_PAUSEAUDIO
• SDL_HINT_AUDIO_DEVICE_APP_NAME
• SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS
• SDL_HINT_GRAB_KEYBOARD
• SDL_HINT_IDLE_TIMER_DISABLED
• SDL_HINT_IME_INTERNAL_EDITING
• SDL_HINT_IME_SHOW_UI
• SDL_HINT_IME_SUPPORT_EXTENDED_TEXT
• SDL_HINT_MOUSE_RELATIVE_MODE_WARP
• SDL_HINT_MOUSE_RELATIVE_SCALING
• SDL_HINT_PS2_DYNAMIC_VSYNC
• SDL_HINT_RENDER_BATCHING
• SDL_HINT_RENDER_LOGICAL_SIZE_MODE
• SDL_HINT_RENDER_OPENGL_SHADERS
• SDL_HINT_RENDER_SCALE_QUALITY
• SDL_HINT_THREAD_STACK_SIZE
• SDL_HINT_VIDEO_EXTERNAL_CONTEXT
• SDL_HINT_VIDEO_FOREIGN_WINDOW_OPENGL
• SDL_HINT_VIDEO_FOREIGN_WINDOW_VULKAN
• SDL_HINT_VIDEO_HIGHDPI_DISABLED
• SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT
• SDL_HINT_VIDEO_X11_FORCE_EGL
• SDL_HINT_VIDEO_X11_XINERAMA
• SDL_HINT_VIDEO_X11_XVIDMODE
• SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING
• SDL_HINT_WINDOWS_FORCE_MUTEX_CRITICAL_SECTIONS
• SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4
• SDL_HINT_WINRT_HANDLE_BACK_BUTTON
• SDL_HINT_WINRT_PRIVACY_POLICY_LABEL
• SDL_HINT_WINRT_PRIVACY_POLICY_URL
• SDL_HINT_XINPUT_USE_OLD_JOYSTICK_MAPPING

## Environment Variable Renames

The following environment variables have been renamed:

• SDL_AUDIODRIVER => SDL_AUDIO_DRIVER
• SDL_PATH_DSP => AUDIODEV
• SDL_VIDEODRIVER => SDL_VIDEO_DRIVER

## Removed Environment Variables

The following environment variables have been removed:

• SDL_AUDIO_ALSA_DEBUG
• SDL_DISKAUDIODELAY
• SDL_DISKAUDIOFILE
• SDL_DISKAUDIOFILEIN
• SDL_DUMMYAUDIODELAY
• SDL_HAPTIC_GAIN_MAX
• SDL_HIDAPI_DISABLE_LIBUSB
• SDL_HIDAPI_JOYSTICK_DISABLE_UDEV
• SDL_INPUT_FREEBSD_KEEP_KBD
• SDL_INPUT_LINUX_KEEP_KBD
• VITA_DISABLE_TOUCH_BACK
• VITA_DISABLE_TOUCH_FRONT
• VITA_MODULE_PATH
• VITA_PVR_OGL
• VITA_PVR_SKIP_INIT
• VITA_RESOLUTION

## Removed Functions

The following functions have been removed:

• SDL_ClearHints() - replaced with SDL_ResetHints()

## Function Renames

The following functions have been renamed:

• SDL_DelHintCallback() => SDL_RemoveHintCallback()
"""
