"""SDL_scancode.h migration guide - SDL2 to SDL3."""

HEADER = "SDL_scancode.h"

MIGRATION_DATA = """
# SDL_scancode.h Migration Guide

## Removed Symbols

The following symbols have been removed:

• SDL_SCANCODE_WWW
• SDL_SCANCODE_MAIL
• SDL_SCANCODE_CALCULATOR
• SDL_SCANCODE_COMPUTER
• SDL_SCANCODE_BRIGHTNESSDOWN
• SDL_SCANCODE_BRIGHTNESSUP
• SDL_SCANCODE_DISPLAYSWITCH
• SDL_SCANCODE_KBDILLUMTOGGLE
• SDL_SCANCODE_KBDILLUMDOWN
• SDL_SCANCODE_KBDILLUMUP
• SDL_SCANCODE_APP1
• SDL_SCANCODE_APP2

## Symbol Renames

The following symbols have been renamed:

• SDL_NUM_SCANCODES => SDL_SCANCODE_COUNT
• SDL_SCANCODE_AUDIOFASTFORWARD => SDL_SCANCODE_MEDIA_FAST_FORWARD
• SDL_SCANCODE_AUDIOMUTE => SDL_SCANCODE_MUTE
• SDL_SCANCODE_AUDIONEXT => SDL_SCANCODE_MEDIA_NEXT_TRACK
• SDL_SCANCODE_AUDIOPLAY => SDL_SCANCODE_MEDIA_PLAY
• SDL_SCANCODE_AUDIOPREV => SDL_SCANCODE_MEDIA_PREVIOUS_TRACK
• SDL_SCANCODE_AUDIOREWIND => SDL_SCANCODE_MEDIA_REWIND
• SDL_SCANCODE_AUDIOSTOP => SDL_SCANCODE_MEDIA_STOP
• SDL_SCANCODE_EJECT => SDL_SCANCODE_MEDIA_EJECT
• SDL_SCANCODE_MEDIASELECT => SDL_SCANCODE_MEDIA_SELECT
"""
